More test cases for clipoard API including some edge cases
neutralinojs/neutralinojs pull request #1223
Opened 2024-03-18 22:38 UTC by Sadaf-A

## Description

This PR adds more test cases for clipoard API including some edge cases

## Changes proposed

 - added test cases for clipboard api

## How to test it

 - Run specs/tests

## Next steps

None.

## Deploy notes

None.

2024-03-19 12:00 UTC, shalithasuranga commented on spec/clipboard.spec.js
> +                await __close(clipboardText1 === clipboardText2 ? 'ok' : 'not ok');
Do you think it's better to do the comparison from Node with `assert` by sending both strings via an object?

2024-03-19 12:02 UTC, shalithasuranga commented on spec/clipboard.spec.js
> +            assert.equal(runner.getOutput(), 'NE_RT_NATRTER');
Seems like we can merge these tests into `throws an error if the parameter is not a string` case?

2024-03-19 12:02 UTC, shalithasuranga commented on spec/clipboard.spec.js
> +                await Neutralino.clipboard.writeText('@#$%^&*');
Can we add some Unicode chars too?

2024-03-19 12:03 UTC, shalithasuranga requested changes
Hello @Sadaf-A. Thanks for sending this. Could you please resolve in-line comments?

Thanks :tada: , let me know if you have questions or ideas

2024-03-20 12:55 UTC, Sadaf-A commented
> Hello @Sadaf-A. Thanks for sending this. Could you please resolve in-line comments?
> 
> Thanks :tada: , let me know if you have questions or ideas

Hey! thanks for the review I've addressed the changes requested by you
please have a look

2024-03-22 10:53 UTC, shalithasuranga approved these changes
Thanks so much @Sadaf-A :tada:

2024-03-22 10:53 UTC, merged