TestSuite: debug API
neutralinojs/neutralinojs pull request #1255
Opened 2024-05-24 13:55 UTC by Sadaf-A

## Description
This PR adds additional testcases for debug API for a better test coverage

## Changes proposed
Following testcases have been added
### debug API
log()
- [x] logs an info message
- [ ] logs a warning message
- [ ] logs a debug message
- [ ] logs a message with special characters
- [ ] handles empty log messages gracefully

## How to test it

 - Run specs/tests

## Next steps

None.

## Deploy notes

None.

2024-05-27 12:07 UTC, shalithasuranga commented on spec/debug.spec.js
> +            assert.ok(runner.getOutput().includes('Hello! This is a info message'));
The `INFO` option outputs the `INFO` word into the logfile, so can we add another assertion for it as well?

2024-05-27 12:08 UTC, shalithasuranga commented on spec/debug.spec.js
> +            assert.ok(runner.getOutput().includes('Hello! This is a warning message'));
The `WARNING` option outputs the `WARNING` word into the logfile, so can we add another assertion for it as well?

2024-05-27 12:09 UTC, shalithasuranga commented on spec/debug.spec.js
> +            assert.ok(runner.getOutput().includes('Hello! This is a debug message'));
The `DEBUG` option outputs the `DEBUG` word into the logfile, so can we add another assertion for it as well?

2024-05-27 12:10 UTC, shalithasuranga requested changes
Thanks for sending this PR @Sadaf-A. I've added some comments to several changes. We can merge this after solving those requested changes mentioned in comments :tada:

2024-05-27 13:09 UTC, Sadaf-A commented
> Thanks for sending this PR @Sadaf-A. I've added some comments to several changes. We can merge this after resolving those requested changes mentioned in comments :tada:

Sure, I'll resolve the comments by the EOD. Thank you for the review!

2024-05-29 10:37 UTC, shalithasuranga approved these changes
Thanks, looks great now :tada:

2024-05-29 10:37 UTC, merged