added: testcases for filesystem API
neutralinojs/neutralinojs pull request #1257
Opened 2024-05-31 21:31 UTC by Sadaf-A

## Description

## Changes proposed

Additional test cases for the filesystem API

## How to test it

 - Run specs/tests

## Next steps

None.

## Deploy notes

None.

2024-06-05 13:09 UTC, shalithasuranga commented on spec/filesystem.spec.js
> +        });
The `filesystem.openFile()` function only accepts one parameter (filename), so can we can turn this test case into something like "creates file identifiers with incremental integers" (or create any test case by yourself that suites here better) ?

2024-06-05 13:12 UTC, shalithasuranga commented on spec/filesystem.spec.js
> -
Could you please let me know why is this EOF checking test case removed? Thanks :tada:

2024-06-05 13:19 UTC, shalithasuranga commented on spec/filesystem.spec.js
> +            assert.ok(!stats.isFile);
Could you please do a quick research and verify whether this works properly on Windows (on GitHub Actions also)? Thanks :tada:

2024-06-05 13:21 UTC, shalithasuranga commented on spec/index.js
> +mocha.timeout(22000);
If possible, could you please add some information to this pull request by explaining why you had to increase this timeout? If you can easily find the failing test case for the previous timeout, you can mention it too.

2024-06-05 13:23 UTC, shalithasuranga requested changes
Thanks so much for sending this PR. We can merge this after resolving the requested changes. Besides, please check why several test cases are failing (except the `app.exit()` function on Windows -- we need to apply a fix for the framework to fix it I guess). Thanks :tada:

2024-06-05 13:54 UTC, Sadaf-A commented
> Thanks so much for sending this PR. We can merge this after resolving the requested changes. Besides, please check why several test cases are failing (except the `app.exit()` function on Windows -- we need to apply a fix for the framework to fix it I guess). Thanks :tada:

Hey, thanks for the review! I'll try to resolve the comments by the EOD

2024-06-05 14:44 UTC, Sadaf-A commented on spec/filesystem.spec.js
> -
Hey, I did not intend on removing it I made another commit to add it back but I think it didn't get pushed. I have pushed another commit to add this back. Thanks 🎉

2024-06-17 06:36 UTC, shalithasuranga approved these changes
Thanks so much @Sadaf-A , looks good now :tada:

2024-06-17 06:41 UTC, shalithasuranga commented on spec/filesystem.spec.js
> +            assert.ok(!stats.isFile);
Hi @Sadaf-A, I removed this test case for now. I don't have a Windows machine to experiment with `/`'s behavior on Windows. Please check -- If `/` is a valid path and if it works properly on Windows, you can re-add the following code with another PR:

```js
        it('returns stats for the file system root', async () => {
            runner.run(`
                let stats = await Neutralino.filesystem.getStats('/');
                await __close(JSON.stringify(stats));
            `);
            let stats = JSON.parse(runner.getOutput());
            assert.ok(typeof stats == 'object');
            assert.ok(stats.isDirectory);
            assert.ok(!stats.isFile);
        });
```

I am not sure whether `/` refers to **root** on standard Windows systems.

Thanks :tada:

2024-06-17 06:41 UTC, merged

2024-06-17 06:57 UTC, shalithasuranga requested changes
Thanks for sending this @Sadaf-A. I only have one comment regarding these changes. We can merge this after resolving it :tada: