GSoC2024: TestSuite - clipboard API
neutralinojs/neutralinojs pull request #1266
Opened 2024-06-22 12:21 UTC by Sadaf-A

## Description
This PR adds test cases to clipboard API for better coverage

## Changes proposed

- writeText()
- [ ] successfully writes an empty string to the clipboard
- [ ] handles concurrent writes to the clipboard
- readText()
- [ ] returns text with newline characters intact
- writeImage()
- [ ] writes an image to the clipboard successfully
- [ ] throws an error when the image data is invalid
- readImage()
- [ ] returns null when the clipboard is empty
- [ ] throws an error when the data is invalid
- [ ] extracts image contents and forms a JSON object
- clear()
- [ ] does nothing if the clipboard is already empty
- getFormat()
- [ ] returns the correct format when the format is text
- [ ] returns the correct format when the format is image
- [ ] returns unknown when the format is unknown
## How to test it

 - Run `cd spec && npm test clipboard`

## Next steps

None.

## Deploy notes

None.

2024-06-24 06:11 UTC, shalithasuranga commented on spec/clipboard.spec.js
> +            assert.equal(runner.getOutput(), 'World');
Do we need to assert `Hello` as well since this test is mentioned as "concurrent"? Thanks

2024-06-24 06:18 UTC, shalithasuranga commented on spec/clipboard.spec.js
> +                await Neutralino.clipboard.writeImage(${JSON.stringify(image)});
`ArrayBuffer` instance won't work with JSON.stringify properly, so please consider moving `let image...` to `runner.run()` from Node. Thanks

2024-06-24 06:20 UTC, shalithasuranga commented on spec/clipboard.spec.js
> +                data: new ArrayBuffer(40000)
Please check my previous comment regarding `ArrayBuffer`

2024-06-24 06:21 UTC, shalithasuranga commented on spec/clipboard.spec.js
> +                data: new ArrayBuffer(40000)
Please check my previous comments regarding `ArrayBuffer`

2024-06-24 06:22 UTC, shalithasuranga requested changes
Hello @Sadaf-A, thanks so much for sending this pull request. I've added note notes. Also, please check the failing test case on macOS. Thanks :tada:

2024-06-24 06:24 UTC, Sadaf-A commented
> Hello @Sadaf-A, thanks so much for sending this pull request. I've added several notes. Also, please check the failing test case on macOS. Thanks :tada:

Sounds great! I will try to resolve them as soon as possible

2024-06-24 18:54 UTC, Sadaf-A commented
> Hello @Sadaf-A, thanks so much for sending this pull request. I've added several notes. Also, please check the failing test case on macOS. Thanks 🎉

Hey, I have made the requested changes. One, testcase is failing for macOS because `getFormat()` is returning `unknown` even when the clipboard contains an image.

2024-06-27 08:23 UTC, shalithasuranga commented
Hi @Sadaf-A Thanks for posting your findings. For now, we can run create an issue similar to [this](https://github.com/neutralinojs/neutralinojs/issues/1260) by mentioning this issue and remove that particular test case from spec. I also noticed a new failing test case on Windows too. Please study about it. If it's also a framework problem, you can do the same :tada:

2024-07-04 12:53 UTC, shalithasuranga approved these changes
Looks great now :) Thanks for your contribution @Sadaf-A :tada:

2024-07-04 12:53 UTC, merged